name_1 = input("Give me a name: ")
name_2 = input("Give me another name: ")
bad_job = input("Give me a job title: ")
job_action = input("Task associated with the job: ")
job_item = input("Item associated with the job: ")
good_job = input("Give me another job title: ")
place_1 = input("Give me a place: ")
number_1 = input("Give me a number: ")
number_2 = input("Give me another number: ")
number_3 = input("Give me one more number: ")
time = input("Give me a unit of time: ")
verb_1 = input("Give me a ver in the past tense: ")
bad_adj = input("Give me a negative sounding adjective: ")
item = input("Give me a random object: ")

print("")

print("Once upon a time, " + name_1 + " worked as a " + bad_job + " at the local " + place_1 + ".")
print(name_1 + " did not like their job very much. In fact, ever since " + name_1 + " was " + number_1 + " years old, they wanted to be a " + good_job + ", however they made do.")
print("But one day " + name_2 + ", " + name_1 + "'s boss demanded that they " +  job_action + " with their " + job_item + " in " + number_2 + " " + time + "s." )
print(name_1 + " yelled. 'Are you " + bad_adj + "?! How am I supposed to do that?' ")
print( name_1 + " " + verb_1 + " their boss, took all " + number_3 + " " + item + "s the company had, and lived happily ever after as a " + good_job + ". ")
print("The End.")
print("           o o ")
print("          _____")
print("          \___/")
